### ISSUE TITLE
Taltos segfaults with 50 move rule checking.

### ISSUE THREAD

**Issue by archtux** [GBuella/Taltos#1]
In revision 99 you change half_move from 50 to 100(ply) but the engine continues crashing at ply 52 because the array is designed for 51 elements.(engine.c:210 static struct position history[51];)
Changing the array size to 102 fixes the segfaults(I've tested with 250 games).
Maybe 101 elements is also sufficient.

**Comment by GBuella** [comment]
That is correct, thanks.

**Comment by GBuella** [comment]
Fixed in: 2a9bc5dd2580a4f667427f1a39cac12ba2d16199
