### ISSUE TITLE
Illegal move always at move 102

### ISSUE THREAD

**Issue by archtux** [GBuella/Taltos#2]
Commit 108 and 109 Taltos makes always an illegal move at move 102 no matter if it plays black or white.
Commit 107 works fine.
The illegal move is a move calculated by Taltos if it was playing the opposite site with position at move 100.

**Comment by GBuella** [comment]
Could you help with a pgn?
I'm just not able to reproduce it.

**Comment by archtux** [comment]
![Uploading Screenshot_20161030_013052.png…]()

**Comment by archtux** [comment]
Here's a screenshot when Taltos calculates a move at move 102 and this occurs in every game at move 102!
https://drive.google.com/open?id=0B-PM8aD2-9I4SG10SmFRaEZid1U

**Comment by GBuella** [comment]
Oh, thanks,
I see it is UCI mode, which is new in commit #102
I'll try to reproduce it with a 100 move game in UCI mode.
Hopefully it doesn't have this bug in xboard mode.

**Comment by archtux** [comment]
You're right.
This doesn't happen in xboard mode.
I saw a game that ended in mate after 127 moves.

**Comment by GBuella** [comment]
Fix in 154e127eb0cb5c7a02b79b687d16004586f075ea
Now instead of going haywire at 102 moves in UCI mode,
it quits at around 6400 moves. I'm too lazy right now to support potentially infinite games.

UCI mode is still very experimental.
